name: llp_ui_iOS
options:
  minimumXcodeGenVersion: 2.0.0
  bundleIdPrefix: com.nd.sdp.component
  deploymentTarget:
    iOS: 12.0
settings:
  GENERATE_INFOPLIST_FILE: YES
targets:
  llp_ui_iOS:
    type: framework.static
    platform: iOS
    sources:
      - path: llp_ui_iOS
        excludes:
          - "src/*.h"
          - "src/**/*.h"
      - path: llp_ui_iOS
        includes:
          - "src/*.h"
          - "src/**/*.h"
        buildPhase: headers
        headerVisibility: project
    scheme:
      testTargets:
        - llp_ui_iOSTests
    settings:
      OTHER_LDFLAGS:
        - "$(inherited)"
      HEADER_SEARCH_PATHS:
        - "$(inherited)"
  llp_ui_iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: llp_ui_iOSTests
    dependencies:
      - target: llp_ui_iOS
    settings:
      OTHER_LDFLAGS:
          - "$(inherited)"
