source 'ssh://git@cocoapods.sdp.nd:/cocoapods-precompiled/specs.git'
source 'ssh://git@cocoapods.sdp.nd:/cocoapods/specs.git'

platform :ios, '13.0'

target 'llp_ui_iOS-Demo' do
  use_frameworks!
  
    root_path = File.join(__dir__, '../')
    podspec_path = File.join(root_path, 'LLPUI.podspec')
    pod 'LLPUI', :path => podspec_path.to_s
    
    pod 'LLPUtils', :git => 'git@git.sdp.nd:component-ios/llp_utils_iOS.git', :branch => 'develop'
    
end
