platform :ios, '13.0'

target 'XUI-Demo' do
  use_frameworks!
  
    pod 'XList', :path => '../XList.podspec'
    pod 'XKit', :git => 'git@github.com:xueqooy/XKit.git', :branch => 'develop'
    pod 'XUI', :path => '../XUI.podspec'
    
    pod 'LookinServer', :configurations => ['Debug']

    
end
