name: llp_ui_iOS-Demo
options:
  minimumXcodeGenVersion: 2.0.0
  bundleIdPrefix: com.nd.sdp.component
  deploymentTarget:
    iOS: 12.0
targets:
  llp_ui_iOS-Demo:
    type: application
    platform: iOS
    info:
      path: llp_ui_iOS-Demo/Info.plist
      properties:
        CFBundleName: "llp_ui_iOS-Demo"
        CFBundleVersion: "1.0.0"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
    sources:
      - path: llp_ui_iOS-Demo
    settings:
      OTHER_LDFLAGS:
        - "$(inherited)"
